const sampleData = {
  products: [
    {
      name: "Mimi",
      slug: "mimi",
      category: "cats",
      description: "Mimi the cat",
      images: ["/images/mimi1.jpg", "/images/mimi2.jpg"],
      price: 9.99,
      brand: "MMM",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Mango",
      slug: "mango",
      category: "cats",
      description: "Mango the cat",
      images: ["/images/mango1.jpg", "/images/mango2.jpg"],
      price: 10.9,
      brand: "MMM",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Misu",
      slug: "misu",
      category: "cats",
      description: "Misu the cat",
      images: ["/images/misu.jpg"],
      price: 99.95,
      brand: "MMM",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
